name: tests-and-linter
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.0.0
      - uses: actions/setup-node@v3.0.0
      - run: make install
      - run: make lint
      - run: make test
